use crate::extractors;
use crate::signatures;

/// IoT-focused subset of Binwalk 3.1.0 magic signatures.
/// Each Signature block below is copied from the upstream 3.1.0 magic.rs;
/// only unrelated formats were removed.
pub fn patterns() -> Vec<signatures::common::Signature> {
    vec![
        signatures::common::Signature {
                    name: "gzip".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::gzip::gzip_magic(),
                    parser: signatures::gzip::gzip_parser,
                    description: signatures::gzip::DESCRIPTION.to_string(),
                    extractor: Some(extractors::gzip::gzip_extractor()),
                },
        signatures::common::Signature {
                    name: "xz".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::xz::xz_magic(),
                    parser: signatures::xz::xz_parser,
                    description: signatures::xz::DESCRIPTION.to_string(),
                    extractor: Some(extractors::lzma::lzma_extractor()),
                },
        signatures::common::Signature {
                    name: "tarball".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::tarball::tarball_magic(),
                    parser: signatures::tarball::tarball_parser,
                    description: signatures::tarball::DESCRIPTION.to_string(),
                    extractor: Some(extractors::tarball::tarball_extractor()),
                },
        signatures::common::Signature {
                    name: "squashfs".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::squashfs::squashfs_magic(),
                    parser: signatures::squashfs::squashfs_parser,
                    description: signatures::squashfs::DESCRIPTION.to_string(),
                    extractor: Some(extractors::squashfs::squashfs_extractor()),
                },
        signatures::common::Signature {
                    name: "lzma".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::lzma::lzma_magic(),
                    parser: signatures::lzma::lzma_parser,
                    description: signatures::lzma::DESCRIPTION.to_string(),
                    //extractor: Some(extractors::sevenzip::sevenzip_extractor()),
                    extractor: Some(extractors::lzma::lzma_extractor()),
                },
        signatures::common::Signature {
                    name: "bzip2".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::bzip2::bzip2_magic(),
                    parser: signatures::bzip2::bzip2_parser,
                    description: signatures::bzip2::DESCRIPTION.to_string(),
                    extractor: Some(extractors::bzip2::bzip2_extractor()),
                },
        signatures::common::Signature {
                    name: "uimage".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::uimage::uimage_magic(),
                    parser: signatures::uimage::uimage_parser,
                    description: signatures::uimage::DESCRIPTION.to_string(),
                    extractor: Some(extractors::uimage::uimage_extractor()),
                },
        signatures::common::Signature {
                    name: "cpio".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::cpio::cpio_magic(),
                    parser: signatures::cpio::cpio_parser,
                    description: signatures::cpio::DESCRIPTION.to_string(),
                    extractor: Some(extractors::sevenzip::sevenzip_extractor()),
                },
        signatures::common::Signature {
                    name: "linux_kernel".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: true,
                    magic: signatures::linux::linux_kernel_version_magic(),
                    parser: signatures::linux::linux_kernel_version_parser,
                    description: signatures::linux::LINUX_KERNEL_VERSION_DESCRIPTION.to_string(),
                    extractor: Some(extractors::linux::linux_kernel_extractor()),
                },
        signatures::common::Signature {
                    name: "linux_boot_image".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::linux::linux_boot_image_magic(),
                    parser: signatures::linux::linux_boot_image_parser,
                    description: signatures::linux::LINUX_BOOT_IMAGE_DESCRIPTION.to_string(),
                    extractor: None,
                },
        signatures::common::Signature {
                    name: "zstd".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::zstd::zstd_magic(),
                    parser: signatures::zstd::zstd_parser,
                    description: signatures::zstd::DESCRIPTION.to_string(),
                    extractor: Some(extractors::zstd::zstd_extractor()),
                },
        signatures::common::Signature {
                    name: "zip".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::zip::zip_magic(),
                    parser: signatures::zip::zip_parser,
                    description: signatures::zip::DESCRIPTION.to_string(),
                    extractor: Some(extractors::sevenzip::sevenzip_extractor()),
                },
        signatures::common::Signature {
                    name: "jffs2".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::jffs2::jffs2_magic(),
                    parser: signatures::jffs2::jffs2_parser,
                    description: signatures::jffs2::DESCRIPTION.to_string(),
                    extractor: Some(extractors::jffs2::jffs2_extractor()),
                },
        signatures::common::Signature {
                    name: "romfs".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::romfs::romfs_magic(),
                    parser: signatures::romfs::romfs_parser,
                    description: signatures::romfs::DESCRIPTION.to_string(),
                    extractor: Some(extractors::romfs::romfs_extractor()),
                },
        signatures::common::Signature {
                    name: "ubi".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::ubi::ubi_magic(),
                    parser: signatures::ubi::ubi_parser,
                    description: signatures::ubi::UBI_IMAGE_DESCRIPTION.to_string(),
                    extractor: Some(extractors::ubi::ubi_extractor()),
                },
        signatures::common::Signature {
                    name: "yaffs".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::yaffs::yaffs_magic(),
                    parser: signatures::yaffs::yaffs_parser,
                    description: signatures::yaffs::DESCRIPTION.to_string(),
                    extractor: Some(extractors::yaffs2::yaffs2_extractor()),
                },
        signatures::common::Signature {
                    name: "cramfs".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::cramfs::cramfs_magic(),
                    parser: signatures::cramfs::cramfs_parser,
                    description: signatures::cramfs::DESCRIPTION.to_string(),
                    extractor: Some(extractors::sevenzip::sevenzip_extractor()),
                },
        signatures::common::Signature {
                    name: "ext".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::ext::ext_magic(),
                    parser: signatures::ext::ext_parser,
                    description: signatures::ext::DESCRIPTION.to_string(),
                    extractor: Some(extractors::tsk::tsk_extractor()),
                },
        signatures::common::Signature {
                    name: "tplink".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::tplink::tplink_magic(),
                    parser: signatures::tplink::tplink_parser,
                    description: signatures::tplink::DESCRIPTION.to_string(),
                    extractor: None,
                },
        signatures::common::Signature {
                    name: "trx".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::trx::trx_magic(),
                    parser: signatures::trx::trx_parser,
                    description: signatures::trx::DESCRIPTION.to_string(),
                    extractor: Some(extractors::trx::trx_extractor()),
                },
        signatures::common::Signature {
                    name: "seama".to_string(),
                    short: false,
                    magic_offset: 0,
                    always_display: true,
                    magic: signatures::seama::seama_magic(),
                    parser: signatures::seama::seama_parser,
                    description: signatures::seama::DESCRIPTION.to_string(),
                    extractor: None,
                },
        signatures::common::Signature {
                    name: "rtk".to_string(),
                    short: true,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::rtk::rtk_magic(),
                    parser: signatures::rtk::rtk_parser,
                    description: signatures::rtk::DESCRIPTION.to_string(),
                    extractor: None,
                },
        signatures::common::Signature {
                    name: "zlib".to_string(),
                    // The magic bytes for this signature are only 2 bytes, only match on the beginning of a file
                    short: true,
                    magic_offset: 0,
                    always_display: false,
                    magic: signatures::zlib::zlib_magic(),
                    parser: signatures::zlib::zlib_parser,
                    description: signatures::zlib::DESCRIPTION.to_string(),
                    extractor: Some(extractors::zlib::zlib_extractor()),
                },
    ]
}
